packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@nestjs/core': true
  '@swc/core': true
  cpu-features: true
  protobufjs: true
  ssh2: true
  unrs-resolver: true

catalog:
  "@babel/core": ^7.29.0
  "@rolldown/plugin-babel": ^0.2.2
  "@tailwindcss/vite": ^4.2.2
  "@types/babel__core": ^7.20.5
  "@types/node": ^24.12.2
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.2.3
  "@vitejs/plugin-react": ^6.0.1
  "@vitest/browser-playwright": ^4.1.4
  "@vitest/coverage-v8": ^4.1.4
  babel-plugin-react-compiler: ^1.0.0
  globals: ^17.4.0
  oxfmt: ^0.45.0
  oxlint: ^1.60.0
  react: ^19.2.4
  react-dom: ^19.2.4
  tailwindcss: ^4.2.2
  typescript: ^6.0.2
  vite: ^8.0.4
  vitest: ^4.1.4
  "@nestjs/common": ^11.0.1
  pg: ^8.20.0
  "@nestjs/testing": ^11.0.1
  "@types/pg": ^8.20.0
  "drizzle-orm": ^0.45.2
  "drizzle-seed": ^0.3.1
  tsdown: ^0.21.8
